# Generated by Django 4.0 on 2022-03-26 14:04

import adminsortable.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=50, verbose_name='Your Name')),
                ('score', models.IntegerField(default=0, verbose_name='Score')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
                ('isTrue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title of Meeting')),
                ('platform', models.CharField(choices=[('IRL', 'Physical Meeting'), ('YT', 'Youtube Live Stream'), ('TW', 'Twitch live')], default='IRL', max_length=3, verbose_name='Type of Meeting : IRL or live stream')),
                ('desc', markdownfield.models.MarkdownField(blank=True, max_length=200, rendered_field='desc_rendered', verbose_name='Description')),
                ('desc_rendered', markdownfield.models.RenderedMarkdownField()),
                ('code', models.CharField(default='Pour1nf0', max_length=50, verbose_name='Security Code for joining the Meeting')),
                ('has_started', models.BooleanField(default=False, verbose_name='Meeting has started')),
                ('reward_fastest', models.BooleanField(default=False, verbose_name='Reward the fastest answers')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start time of the meeting')),
                ('date_end', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End time of the meeting')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image for your meeting')),
                ('stream_url', models.URLField(blank=True, null=True, verbose_name='URL for Youtube live stream (only if platform is Youtube)')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.choice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.attendee')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Question')),
                ('desc', markdownfield.models.MarkdownField(max_length=800, rendered_field='desc_rendered', verbose_name='Description')),
                ('desc_rendered', markdownfield.models.RenderedMarkdownField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('is_done', models.BooleanField(default=False, verbose_name='Question already completed')),
                ('question_type', models.CharField(choices=[('PL', 'Poll'), ('TX', 'Text Only'), ('QZ', 'Quizz'), ('WC', 'Word Cloud')], default='PL', max_length=2, verbose_name='Type of Question')),
                ('question_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
                ('first_correct_answer', models.BooleanField(default=True, verbose_name='True if no one gave the correct answer already')),
                ('meeting', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.meeting')),
            ],
            options={
                'ordering': ['question_order'],
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.question'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.meeting'),
        ),
    ]
