# Generated by Django 4.0 on 2022-01-19 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_alter_meeting_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='code',
            field=models.CharField(default='Pour1nf0', max_length=50, verbose_name='Security Code for joining the Meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 17, 59, 9, 6828, tzinfo=utc), verbose_name='End time of the meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image for your meeting'),
        ),
    ]
