# Generated by Django 4.0 on 2022-01-17 15:34

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0030_alter_meeting_date_end_alter_meeting_date_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 17, 34, 22, 56005, tzinfo=utc), verbose_name='End time of the meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start time of the meeting'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='desc',
            field=markdownfield.models.MarkdownField(blank=True, max_length=200, rendered_field='desc_rendered', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=markdownfield.models.MarkdownField(max_length=800, rendered_field='desc_rendered', verbose_name='Description'),
        ),
    ]
