# Generated by Django 4.0 on 2022-01-17 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0031_alter_meeting_date_end_alter_meeting_date_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 17, 58, 30, 126640, tzinfo=utc), verbose_name='End time of the meeting'),
        ),
    ]
