# Generated by Django 4.0 on 2022-01-17 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0032_alter_meeting_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 18, 0, 6, 445066, tzinfo=utc), verbose_name='End time of the meeting'),
        ),
    ]
