# Generated by Django 4.0 on 2022-03-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topTitle_ln1', models.CharField(default='LibreKast Meetings', max_length=30, verbose_name='Title (first line)')),
                ('topTitle_ln2', models.CharField(default='Gamify your meetings', max_length=30, verbose_name='Title (second line)')),
                ('topDes', models.TextField(default='Create animations for your meetings such as Quizzes, Polls and Word Clouds. This application is a dummy app showcasing the functionalities. Please bear in mind that this code is made free to help but this app was not designed by actual devs.', max_length=300, verbose_name='App Description')),
                ('btn1Text', models.CharField(default=' Vote Now', max_length=30, verbose_name='Button 1 Text')),
                ('btn2Text', models.CharField(default=' Know More', max_length=30, verbose_name='Button 2 Text')),
                ('btn2Url', models.CharField(default=' https://github.com/RduMarais/LibreKast', max_length=40, verbose_name='Button 2 URL')),
                ('midTitle', models.CharField(default='How to deploy', max_length=30, verbose_name='Title 1st paragraph')),
                ('midDesc', models.TextField(default='A comprehensive guide to deployment is available on GitHub README. In order to setup LibreKast in an deployment envionment, one needs to setup a web server (such as Apache or Nginx), setup the server for delivering a django app and clone the repository to start the app. Then for deployment a comprehensive checklist is available on GitHub to explain how to seed the application secrets; remove debugging functionalities; create an admin user etc.', max_length=430, verbose_name='Content 1st paragraph')),
                ('teamTitle', models.CharField(default='State of the development ', max_length=30, verbose_name='Title 2nd paragraph')),
                ('teamDesc', models.TextField(default='The current app was designed by Romain du Marais for personal use and shared publicly on GitHub ; and Aahnik Daw for a school project. Please contribute to its development if you consider it useful.', max_length=300, verbose_name='Content 2nd paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Name')),
                ('role', models.CharField(max_length=20, verbose_name='Role')),
                ('bio', models.CharField(max_length=50, verbose_name='About')),
                ('imgUrl', models.URLField(verbose_name='Image URL')),
            ],
        ),
    ]
