# Generated by Django 4.0 on 2022-01-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='midDesc',
            field=models.TextField(default='A comprehensive guide to deployment is available on GitHub README. In order to setup LibreKast in an deployment envionment, one needs to setup a web server (such as Apache or Nginx), setup the server for delivering a django app and clone the repository to start the app. Then for deployment a comprehensive checklist is available on GitHub to explain how to seed the application secrets; remove debugging functionalities; create an admin user etc.', max_length=400, verbose_name='Content 1st paragraph'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='teamDesc',
            field=models.TextField(default='The current app was designed by Romain du Marais for personal use and shared publicly on GitHub ; and Aahnik Daw for a school project. Please contribute to its development if you consider it useful.', max_length=300, verbose_name='Content 2nd paragraph'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='topDes',
            field=models.TextField(default='Create animations for your meetings such as Quizzes, Polls and Word Clouds. This application is a dummy app showcasing the functionalities. Please bear in mind that this code is made free to help but this app was not designed by actual devs.', max_length=300, verbose_name='App Description'),
        ),
    ]
